name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: copy file via ssh password
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build --if-present  