name: deploy vuejs
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: build vuejs project
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm run build --if-present  